  services:
    server:
      restart: "no"
      ports:
        - "8080:8080"
      build:
        context: .
      command:
        - fastapi
        - run
        - --port
        - "8080"
        - --reload
        - "app/main.py"
      develop:
        watch:
          - path: ./app
            action: sync
            target: /app
            ignore:
              - .venv
          - path: pyproject.toml
            action: rebuild
