  services:
    server:
      restart: "no"
      ports:
        - "8080:8080"
      build:
        context: .
      command:
        - fastapi
        - run
        - --port
        - "8080"
        - --reload
        - "app/main.py"
