services:
  employees-api:
    restart: "no"
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: ./cmd/api/**/*.go
        - action: rebuild
          path: ./go.mod
        - action: rebuild
          path: ./go.sum
